### ISSUE TITLE
Графическая часть программы

### ISSUE THREAD

**Issue by dmitrymack** [topteamsibsutis/IP_Calculator#2]

**Comment by HappySKN** [comment]
Необходимо создать окно программы используя API "Windows Form". Окно включает в себя поле для ввода IP-адреса, выпадающий список из всех возможных масок подсети, а также кнопки "Рассчитать данные сети" Которая передаёт данные из поля для IP-адреса и поля для маски подсети в функции подсчёта Wildcard, Broadcast и т.д.

**Comment by HappySKN** [comment]
Для вывода подсчитанных данных необходимо создать поля для всех данных, а именно: Wildcard, Network adress, First host, Last host, Broadcast, Quantity of IP-adresses, Quantity of IP-adresses used.

**Comment by HappySKN** [comment]
Доработать дизайн программы: добавить фон, изменить иконку, имя заголовка, одним словом, сделать приятную глазу программу.

**Comment by HappySKN** [comment]
Создать кнопку "записать в текстовый файл" которая будет вызывать функцию записи в текстовый файл.

**Comment by HappySKN** [comment]
Кнопка "Записать в текстовый файл" называется "Create text file" и реализована на ветке develop_text
